WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

BALL_RADIUS = WINDOW_WIDTH // 160
BALL_INITIAL_MAX_SPEED = 600
BALL_INITIAL_MIN_SPEED = 400

PADDLE_WIDTH = WINDOW_WIDTH // 45
PADDLE_HEIGHT = WINDOW_HEIGHT // 7
PADDLE_SPEED = 500

FPS = 60

WIN_SCORE = 10

NET_SEGMENTS = 20
NET_SEGMENTS_GAP = 10
NET_SEGMENT_HEIGHT = (WINDOW_HEIGHT - ((NET_SEGMENTS - 1)
                                       * NET_SEGMENTS_GAP)) // NET_SEGMENTS
NET_SEGMENT_WIDTH = WINDOW_WIDTH // 100

PADDLE_TOLERANCE_BEGINNER = (220, 420)
PADDLE_TOLERANCE_INTERMEDIATE = (420, 620)
PADDLE_TOLERANCE_EXPERT = (820, 1020)

PADDLE_SPEED_INCREASE_BEGINNER = 1.03
PADDLE_SPEED_INCREASE_INTERMEDIATE = 1.06
PADDLE_SPEED_INCREASE_EXPERT = 1.12

PADDLE_SPECIAL_HIT_THRESHOLD = 10
PADDLE_SPECIAL_HIT_INCREASE = 1.5
